version: '3'

services:
  lab-survey-front:
    image: lab-survey-front
    container_name: lab-survey-front
    build:
      context: .
      dockerfile: lab-survey-front/Dockerfile
    environment:
      REDIS: lab-survey-redis
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:5000"

  lab-survey-redis:
    image: redis
    container_name: lab-survey-redis
    ports:
        - "6379:6379"
